import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { ClerkProvider } from '@clerk/nextjs';
import localFont from 'next/font/local';
import type { Viewport } from 'next';
import { ThemeProvider } from '@/components/theme-provider';
import { StyleSwitcher } from '@/components/style-switcher';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};
const myFont = localFont({
	src: './nunito-v2.woff2',
	display: 'swap',
});
export const viewport: Viewport = {
	themeColor: { media: '(prefers-color-scheme: dark)', color: 'black' },
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body
					className={cn(
						'min-h-screen, bg-background font-sans antialiased',
						myFont.style
					)}>
					<ThemeProvider attribute="class" defaultTheme="light">
						<div className="relative flex min-h-screen flex-col">
							<main className="grow">{children}</main>
						</div>
					</ThemeProvider>
					<StyleSwitcher />
				</body>
			</html>
		</ClerkProvider>
	);
}
