import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { ClerkProvider } from '@clerk/nextjs';
import type { Viewport } from 'next';
import { ThemeProvider } from '@/components/theme-provider';
import { StyleSwitcher } from '@/components/style-switcher';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export const viewport: Viewport = {
	themeColor: { media: '(prefers-color-scheme: dark)', color: 'black' },
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body
					className={cn(
						'min-h-screen, bg-background font-sans antialiased',
						inter.variable
					)}>
					<ThemeProvider attribute="class" defaultTheme="dark">
						{children}
					</ThemeProvider>
					<StyleSwitcher />
				</body>
			</html>
		</ClerkProvider>
	);
}
